### ISSUE TITLE
Create a panel to render the inputs and the buttons, and create the elements to the tooltip

### ISSUE THREAD

**Issue by MarioRodriguezS** [kommitters/editorjs-tooltip#18]
This issue is part of the Epic #12

### Context.

At this moment, the block is rendered with two inputs, the first one to insert the button text and the other one to insert the tooltip text. Also, a div to create the tooltip was added in the block. 
![Captura del escritorio de 06-10-21 10 55 49](https://user-images.githubusercontent.com/64106728/136240283-0661a5be-822f-4044-8c14-484fc5f72d4e.gif)

### Describe the solution you'd like

The idea is to add a panel to insert the tooltip and create the tooltip elements in the block, the last will be rendered when the user creates the tooltip or when the data is passed through the Editor instance. It is possible to be guided by the panel implemented in the [inline-image](https://github.com/kommitters/editorjs-inline-image) plugin.

**Comment by juanhurtado10** [comment]
@MarioRodriguezS I'd suggest selecting the text and then adding the tooltip text. The same UX from the links. What do you think?

![image](https://user-images.githubusercontent.com/1649973/136243196-e49577e0-47b6-48f4-96da-54de29f63625.png)
