### ISSUE TITLE
when error ，the tip will never hide

### ISSUE THREAD

**Issue by jeasoncc** [kommitters/editorjs-tooltip#47]
Thanks  author for providing this plugin
i use it and feel great

This is a problem I found during use

when error ，the tip will never hide

**Comment by MarioRodriguezS** [comment]
> Thanks author for providing this plugin i use it and feel great
> 
> This is a problem I found during use
> 
> when error ，the tip will never hide

@jeasoncc ,Thanks a lot for report the issue! 

Could you please add more details about when the error raises?, 

Thanks again, Best
Mario

**Comment by CristhianRodriguezMolina** [comment]
> Thanks author for providing this plugin i use it and feel great
> 
> This is a problem I found during use
> 
> when error ，the tip will never hide

Hi, @jeasoncc thanks for the report, but by my part I have couldn't replicate some similar error.

Is this problem still showing to you? if so, can you give us a little bit more context?

**Comment by juanhurtado10** [comment]
Closing this until more info is collected.
