### ISSUE TITLE
The plugin is not working

### ISSUE THREAD

**Issue by LucasBRamos** [kommitters/editorjs-tooltip#48]
### Description

I have several editors on my page and for that reason the editor ids are generated dynamically and this makes the plugin not work like the spread one.

The plugin code expects the Editorjs reference to exist on the page with id editorjs, and in my case, it doesn't.

After trying to understand why, I found within the code on line 133 of the index.js file a fixed reference to an element with the id editorjs.

Is it possible to add an extra parameter so that you can inform the ID instead of having it fixed?

### Environment

* Editor.js version: 2.22.3
* Plugins you use with their versions: 1.1.1
* Device, Browser, OS: All

### Current behavior

When Editorjs id is not editorjs the tooltip plugin does not work.

### Additional context

The editor ids are dynamic, generated according to the page load, so you cannot statically use the editorjs id

**Comment by MarioRodriguezS** [comment]
@LucasBRamos Hi there!.
Thanks a lot for report the issue, we are working to fix it as soon as possible.

**Comment by MarioRodriguezS** [comment]
@LucasBRamos The issue was solved, and the plugin was updated, now you can install the new version (1.1.2). Thanks again!

Best, 
Mario
