### ISSUE TITLE
Error using Yarn for development mode

### ISSUE THREAD

**Issue by BensenHsu** [kommitters/editorjs-tooltip#93]
### Precheck

- [✓] Do a quick search and make sure the bug has not been reported yet.
- [✓] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [✓] Finally, be nice and have fun!.

### Description

Thank you for creating this amazing tool! When I want to enter the development mode on my local environment, I used the command `yarn build:dev` in my VSCode Terminal and I saw this:
```
yarn run v1.22.19
warning ../../package.json: No license field
$ webpack --mode development --watch
/bin/sh: webpack: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

* Editor.js version: n.a.
* Plugins you use with their versions: tooltip
* Device, Browser, OS: MacOS

### Current behavior

1. pull this repository using VSCode
2. Type `yarn build:dev` in VSCode Terminal
3. The error appears

### Expected behavior

```
yarn run v1.22.19
warning ../../package.json: No license field
$ webpack --mode development --watch
/bin/sh: webpack: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by BensenHsu** [comment]
> 

Hi @juanhurtado10, I managed to run `yarn build:dev`, but I found it not what I'm looking for.

I want to preview the tool while I'm developing and changing its style. Is there a way to do that? Thanks!

**Comment by miguelnietoa** [comment]
Hey, @BensenHsu 👋🏻 glad you linked the tool!

1. First, make sure you have all the necessary dependencies installed by running `yarn install`. (I think you missed this)
2. Next, build the development version of the tool with `yarn build:dev`.
3. Finally, use `yarn link` to link `editorjs-tooltip` with your local changes in any other project as a dependency. This will allow you to preview the tool.

Let me know if these instructions work for you. 👍🏻

**Comment by BensenHsu** [comment]
> Hey, @BensenHsu 👋🏻 glad you linked the tool!
> 
> If you want to preview the tool while developing, here's how you can do it:
> 
> 1. First, make sure you have all the necessary dependencies installed by running `yarn install`. (I think you missed this)
> 2. Next, build the development version of the tool with `yarn build:dev`.
> 3. Finally, use `yarn link` to link `editorjs-tooltip` with your local changes in any other project as a dependency. This will allow you to preview the tool.
> 
> Let me know if these instructions work for you. 👍🏻

@miguelnietoa. Thank you very much for the detailed explanation👍, but I don't quite understand the third step. so I use `yarn link` in the `editorjs-tooltip` repository, then the npm public package: `editorjs-tooltip` is renewed? And I `npm install editorjs-tooltip` in my own project?

By the way, I'm trying to use StepSecurity, but can only get this 3 automation, the "Publish to npm" does not work, please enlighten me. Thank you!
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/51500098/211025729-d0cab4ae-fe02-46b4-b281-39b24eec9831.png">

**Comment by miguelnietoa** [comment]
Regarding the first point:
- Yes, run `yarn link` in the `editorjs-tooltip` repository where you made changes.
- Then, navigate to the directory of the project where you want to use your local version of the library, and run `yarn link "editorjs-tooltip"`. This will link the local version of the library to your project in order to preview the changes.

More info: https://classic.yarnpkg.com/lang/en/docs/cli/link/

<br>

Regarding the other point:
To trigger the "Publish to npm" workflow you must create a GitHub release located [here](https://github.com/kommitters/editorjs-tooltip/releases).

Look at the publish.yml file that indicates that this action will be executed when a release is created. 
https://github.com/kommitters/editorjs-tooltip/blob/main/.github/workflows/publish.yml#L1-L4

**Comment by BensenHsu** [comment]
> Regarding the first point:
> 
> * Yes, run `yarn link` in the `editorjs-tooltip` repository where you made changes.
> * Then, navigate to the directory of the project where you want to use your local version of the library, and run `yarn link "editorjs-tooltip"`. This will link the local version of the library to your project in order to preview the changes.
> 
> More info: https://classic.yarnpkg.com/lang/en/docs/cli/link/
> 
> 
> Regarding the other point: To trigger the "Publish to npm" workflow you must create a GitHub release located [here](https://github.com/kommitters/editorjs-tooltip/releases).
> 
> Look at the publish.yml file that indicates that this action will be executed when a release is created.
> 
> https://github.com/kommitters/editorjs-tooltip/blob/f80d4ef8e07c8bc2063720065336b5734ca61d07/.github/workflows/publish.yml#L1-L4

@miguelnietoa Thank you so much! Now I understand the first point.

For the second point, do I have to create the GitHub release manually? I saw on "Publish to npm" repository, that if I change the version in `package.json` and put "Release 1.2.3" in commit message, then it will automatically trigger the "Publish to npm". I tried, but it does not work.

**Comment by miguelnietoa** [comment]
@BensenHsu You must manually create the release in GitHub, and this will do it in npm!

**Comment by miguelnietoa** [comment]
@BensenHsu Closing this. Feel free to reopen if necessary  👌🏻 

Best!

**Comment by BensenHsu** [comment]
> @BensenHsu Closing this. Feel free to reopen if necessary 👌🏻
> 
> Best!

No problem! Thank you!

**Comment by BensenHsu** [comment]
> @BensenHsu You must manually create the release in GitHub, and this will do it in npm!

Hi @miguelnietoa. It's me again 😂. I tried to push the package to npm by following your guidance. But the following error occurs:
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/51500098/211072975-700e9bc8-c008-4f6d-9403-e27fab0f7168.png">

**Comment by BensenHsu** [comment]
This is the repository for this error: https://github.com/BensenHsu/editorjs-tooltip
