### ISSUE TITLE
Change tooltip style by using Joy UI Tooltip component

### ISSUE THREAD

**Issue by BensenHsu** [kommitters/editorjs-tooltip#99]
### Is your feature request related to a problem? Please describe.

1. When the content is too long, the tooltip cannot wrap, so it will be blocked beyond the edge of the browser
<img width="703" alt="image" src="https://user-images.githubusercontent.com/51500098/215410842-81cb1865-5301-48b0-9a06-9e9e11d2d2c3.png">

2. The default tooltip style is hard coded, so cannot display other information such as images.

### Describe the solution you'd like

Joy UI Tooltip component: https://mui.com/joy-ui/react-tooltip/#common-examples
I want to use Joy UI to replace the CodeX tooltip in the code to solve the above problems. However, the tooltip does not work as I change the code to the screenshot below:
<img width="736" alt="image" src="https://user-images.githubusercontent.com/51500098/215411469-4c5b04b5-eff0-45c9-a362-2a53736cb0d0.png">

### Describe alternatives you've considered

Can also use Tippy.js: https://tippyjs.bootcss.com/getting-started/

### Additional context

@miguelnietoa @luishurtado @juanhurtado10 Could you please take a look? Much appreciated!!!

**Comment by BensenHsu** [comment]
Hi @miguelnietoa !

**Comment by miguelnietoa** [comment]
Hi @BensenHsu, thanks for submitting this feature request! 

What you propose is that the plugin can accept HTML code to be rendered as the tooltip.
In this way, being more customizable and allowing to display of other information such as images, right?

**Comment by BensenHsu** [comment]
> 

Yea! Exactly!

**Comment by BensenHsu** [comment]
> Hi @BensenHsu, thanks for submitting this feature request!
> 
> What you propose is that the plugin can accept HTML code to be rendered as the tooltip. In this way, being more customizable and allowing to display of other information such as images, right?

@miguelnietoa Yea! Exactly!

**Comment by BensenHsu** [comment]
@miguelnietoa I tried to change the file to .tsx, it accepted HTML, but the tooltip did not show up.

**Comment by miguelnietoa** [comment]
Hey @BensenHsu, could you please provide a code sandbox (https://codesandbox.io/) to understand in depth the feature request?
